### PR TITLE
Adds the Italian language

### PR DESCRIPTION
**Pull request by OCTIPI1**

### CODE REVIEW

**Comment by krafs** [comment]
Thanks you for the contribution! Will release soon :)

**Comment by OCTIPI1** [comment]
Thanks for the release.
Could you kindly add the lable "hacktoberfest-accepted" to the PR? I would like this PR to count for my Hacktoberfest.

**Comment by krafs** [comment]
Of course :) Good luck!

**Comment by OCTIPI1** [comment]
Thank you very much!

**Pull request merged**
